export function createCustomizingModule(ctx) {
	const { root, urls, apiBase, state } = ctx
	const api = (...args) => ctx.api(...args)
	const branchUrl = (...args) => ctx.branchUrl(...args)
	const checklistManageUrl = (...args) => ctx.checklistManageUrl(...args)
	const checklistUrl = (...args) => ctx.checklistUrl(...args)
	const deliveryChannels = (...args) => ctx.deliveryChannels(...args)
	const deregistrationTemplateUrl = (...args) => ctx.deregistrationTemplateUrl(...args)
	const documentTemplateUrl = (...args) => ctx.documentTemplateUrl(...args)
	const documentTemplateOptionsUrl = (...args) => ctx.documentTemplateOptionsUrl(...args)
	const esc = (...args) => ctx.esc(...args)
	const field = (...args) => ctx.field(...args)
	const invoiceSettingsUrl = (...args) => ctx.invoiceSettingsUrl(...args)
	const schedulingUrl = (...args) => ctx.schedulingUrl(...args)
	const render = (...args) => ctx.render(...args)
	const showTextPreview = (...args) => ctx.showTextPreview(...args)
	const title = (...args) => ctx.title(...args)
	const workflowUrl = (...args) => ctx.workflowUrl(...args)
	const confirmAction = (...args) => ctx.confirmAction(...args)
	const promptAction = (...args) => ctx.promptAction(...args)
	const notifySuccess = (...args) => ctx.notifySuccess(...args)
	const notifyError = (...args) => ctx.notifyError(...args)
	const download = (...args) => ctx.download(...args)

	function documentTemplatesView() {
		const files = state.documentTemplateOptions.files || []; const subfolders = state.documentTemplateOptions.subfolders || []
		const cards = state.documentTemplates.map((entry) => `<article class="bp-checklist-editor" data-document-template="${entry.id}"><div class="bp-form-grid"><label><span>Vorlagenschlüssel</span><input name="key" value="${esc(entry.key)}" pattern="[A-Za-z0-9_-]+" ${entry.id ? 'readonly' : 'required'}></label><label><span>Bezeichnung</span><input name="name" value="${esc(entry.name)}" required></label><label><span>Kategorie</span><input name="category" value="${esc(entry.category)}"></label><label><span>DOCX-Datei aus Bestatter/Vorlagen</span><select name="fileName" required><option value="">Bitte auswählen</option>${files.map((file)=>`<option value="${esc(file.fileName)}" ${file.fileName===entry.fileName?'selected':''}>${esc(file.label||file.fileName)}</option>`).join('')}</select></label><label><span>Ziel-Unterordner der Fallakte</span><select name="outputSubfolder" required><option value="">Bitte auswählen</option>${subfolders.map((folder)=>`<option value="${esc(folder)}" ${folder===entry.outputSubfolder?'selected':''}>${esc(folder)}</option>`).join('')}</select></label><label><span>Sortierung</span><input name="sortOrder" type="number" value="${Number(entry.sortOrder || 0)}"></label></div><label><span>Beschreibung</span><textarea name="description">${esc(entry.description)}</textarea></label><details><summary>Technische Pflichtfelder</summary><p class="bp-muted">Kommagetrennte gültige Stammdatenfelder. Unbekannte Schlüssel werden beim Speichern abgewiesen.</p><input name="requiredFields" value="${esc((entry.requiredFields || []).join(', '))}" list="document-required-fields"></details><div class="bp-inline-options"><label class="bp-inline-check"><input name="supportsPdf" type="checkbox" ${entry.supportsPdf ? 'checked' : ''}> PDF-Ausgabe</label><label class="bp-inline-check"><input name="active" type="checkbox" ${entry.active ? 'checked' : ''}> Aktiv</label></div><p class="bp-card-state" aria-live="polite"></p><div class="bp-row-actions"><button class="bp-secondary preview-document-template" type="button">Vorschau</button><button class="bp-secondary save-document-template" data-id="${entry.id}">Speichern</button>${entry.id ? `<button class="bp-secondary duplicate-document-template" type="button" data-id="${entry.id}">Duplizieren</button><button class="bp-danger delete-document-template" data-id="${entry.id}">Löschen</button>` : ''}</div></article>`).join('')
		return `<section class="bp-panel bp-config-admin"><datalist id="document-required-fields">${(state.documentTemplateOptions.requiredFields||[]).map((name)=>`<option value="${esc(name)}"></option>`).join('')}</datalist><div class="bp-panel-head"><div><h3>Dokumentenvorlagen</h3><p class="bp-muted">Vorlagen konfigurieren und im Nextcloud-Ordner Bestatter/Vorlagen bereitstellen. Vorhandene individuelle Dateien werden niemals überschrieben.</p></div><div class="bp-head-actions"><button type="button" class="bp-secondary" id="download-template-fields">Feldkatalog als CSV</button><button class="bp-secondary" id="provision-templates">Fehlende Standardvorlagen ergänzen</button><button class="bp-primary" id="new-document-template">+ Dokumentenvorlage</button></div></div><div class="bp-token-help"><h4>Verfügbare Vorlagenfelder</h4><p>Der CSV-Katalog enthält alle unterstützten Platzhalter, sprechende Klarnamen und die jeweilige Datenquelle. Er kann jederzeit erneut heruntergeladen werden.</p></div><div class="bp-admin-list">${cards || '<p class="bp-empty">Noch keine Dokumentenvorlagen vorhanden.</p>'}</div></section>`
	}

	function deregistrationTemplatesView() {
		const cards = state.deregistrationTemplates.map((entry) => `<article class="bp-checklist-editor" data-dereg-template="${entry.id}"><div class="bp-form-grid"><label><span>Vorgangsschlüssel</span><input name="key" value="${esc(entry.key)}" pattern="[A-Za-z0-9_-]+" ${entry.id ? 'readonly' : 'required'}></label><label><span>Bezeichnung</span><input name="name" value="${esc(entry.name)}" required></label><label><span>Empfängertyp</span><input name="recipientType" value="${esc(entry.recipientType || '')}"></label><label><span>Nextcloud-Kontaktgruppe</span><input name="contactCategory" value="${esc(entry.contactCategory)}"></label><label><span>Zulässige Übertragungswege</span><input name="deliveryChannels" value="${esc(entry.deliveryChannels.join(', '))}" placeholder="EMAIL, POST, PORTAL, TELEFON"></label><label><span>Formulartyp</span><select name="formType"><option value="STANDARD" ${entry.formType === 'STANDARD' ? 'selected' : ''}>Standard</option><option value="PENSION_SERVICE" ${entry.formType === 'PENSION_SERVICE' ? 'selected' : ''}>Rentenservice</option></select></label><label><span>Wiedervorlage in Tagen</span><input name="followUpDays" type="number" min="0" value="${entry.followUpDays || 0}"></label><label><span>Dokumentvorlagen-Schlüssel</span><input name="documentTemplateKey" value="${esc(entry.documentTemplateKey || '')}"></label></div><label><span>Betreff-Vorlage</span><input name="subjectTemplate" value="${esc(entry.subjectTemplate)}"></label><label><span>Text-Vorlage</span><textarea name="bodyTemplate" rows="6">${esc(entry.bodyTemplate)}</textarea></label><details><summary>Technische Felder und Status</summary><label><span>Pflichtfelder</span><input name="requiredFields" value="${esc((entry.requiredFields || []).join(', '))}"></label><label><span>Zulässige Status</span><input name="allowedStatuses" value="${esc((entry.allowedStatuses || []).join(', '))}"></label></details><label class="bp-inline-check"><input name="active" type="checkbox" ${entry.active ? 'checked' : ''}> Aktiv</label><p class="bp-card-state" aria-live="polite"></p><div class="bp-row-actions"><button class="bp-secondary preview-dereg-template" type="button">Vorschau</button><button class="bp-secondary save-dereg-template" data-id="${entry.id}">Speichern</button>${entry.id ? `<button class="bp-danger delete-dereg-template" data-id="${entry.id}">Löschen</button>` : ''}</div></article>`).join('')
		return `<section class="bp-panel bp-config-admin"><div class="bp-panel-head"><div><h3>Abmeldungen</h3><p class="bp-muted">Empfängergruppen und bearbeitbare Entwürfe; ein automatischer Versand findet nicht statt.</p></div><button class="bp-primary" id="new-dereg-template">+ Abmeldevorgang</button></div><div class="bp-admin-list">${cards || '<p class="bp-empty">Noch keine Abmeldevorgänge vorhanden.</p>'}</div></section>`
	}

	function workflowAdminView() {
		const selectedId = state.workflowAdmin.some((item) => Number(item.id) === Number(state.workflowAdminId)) ? Number(state.workflowAdminId) : Number(state.workflowAdmin[0]?.id || 0)
		state.workflowAdminId = selectedId
		const workflow = state.workflowAdmin.find((item) => Number(item.id) === selectedId)
		const navigation = state.workflowAdmin.map((entry, index) => `<div class="bp-workflow-nav-row ${Number(entry.id) === selectedId ? 'active' : ''}" data-workflow-order-row="${Number(entry.id)}">
			${entry.id ? dragControls('workflow', index, entry.name) : '<span class="bp-new-marker">Neu</span>'}
			<button type="button" class="bp-workflow-select" data-workflow-select="${Number(entry.id)}"><span>${esc(entry.name || 'Neuer Workflow')}</span><small>${esc(entry.key || 'Schlüssel noch festlegen')} · ${entry.actions?.length || 0} Aktionen</small></button>
		</div>`).join('')
		return `<section class="bp-panel bp-custom-table bp-workflow-admin"><div class="bp-panel-head"><div><h3>Workflows und Automatisierungen</h3><p class="bp-muted">Workflows tabellarisch pflegen. Workflows und Folgeaktionen lassen sich am Griff verschieben; die fachlichen Regeln bleiben vollständig erhalten.</p></div><button class="bp-primary" id="new-workflow">+ Workflow</button></div><div class="bp-value-list-workspace bp-workflow-workspace"><nav class="bp-value-list-nav bp-workflow-nav" id="workflow-order-rows" aria-label="Workflows">${navigation}</nav><div class="bp-value-list-editor">${workflow ? workflowEditor(workflow) : '<p class="bp-empty">Noch keine Workflows vorhanden. Mit „Workflow“ beginnen.</p>'}</div></div></section>`
	}

	function workflowActionRows(actions = []) {
		return actions.map((action, index) => `<tr class="bp-workflow-action-row" data-workflow-action-row>
			<td class="bp-value-position">${dragControls('workflow-action', index, action.label || 'Neue Aktion')}</td>
			<td><input class="workflow-action-key" value="${esc(action.key || '')}" aria-label="Aktionsschlüssel, Zeile ${index + 1}" required></td>
			<td><select class="workflow-action-type" aria-label="Aktionstyp, Zeile ${index + 1}">${[['TASK', 'Folgeaufgabe'], ['REMINDER', 'Wiedervorlage'], ['SCHEDULE', 'Termin / Frist'], ['DOCUMENT', 'Dokument'], ['DOCUMENT_BUNDLE', 'Dokumentpaket'], ['EMAIL_DRAFT', 'E-Mail-Entwurf'], ['CONTACT_ACTIVITY', 'Kontaktaktivität'], ['CASE_STATUS', 'Fallstatus ändern']].map(([value, label]) => `<option value="${value}" ${value === (action.type || 'TASK') ? 'selected' : ''}>${label}</option>`).join('')}</select></td>
			<td><input class="workflow-action-label" value="${esc(action.label || '')}" aria-label="Schaltflächentext, Zeile ${index + 1}" required></td>
			<td class="bp-workflow-action-detail"><details><summary>Inhalt und Logik</summary><div class="bp-workflow-action-fields">
				<label data-action-field="title" class="bp-span-2"><span>Titel / Betreff</span><input class="workflow-action-title" value="${esc(action.title || '')}" placeholder="z. B. Termin {{case.number}}"></label>
				<label data-action-field="description" class="bp-span-2"><span>Beschreibung</span><textarea class="workflow-action-description" rows="3">${esc(action.description || '')}</textarea></label>
				<label data-action-field="offset"><span>Fällig in Tagen</span><input class="workflow-action-offset" type="number" min="-30" max="365" value="${Number(action.dueOffsetDays || 0)}"></label>
				<label data-action-field="priority"><span>Priorität</span><select class="workflow-action-priority">${['HOCH', 'NORMAL', 'NIEDRIG'].map((value) => `<option ${value === (action.priority || 'NORMAL') ? 'selected' : ''}>${value}</option>`).join('')}</select></label>
				<label data-action-field="template"><span>Dokumentvorlage</span><select class="workflow-action-template"><option value="">– keine –</option>${state.documentTemplates.map((entry) => `<option value="${esc(entry.key)}" ${entry.key === (action.templateKey || '') ? 'selected' : ''}>${esc(entry.name)}</option>`).join('')}</select></label>
				<label data-action-field="templates" class="bp-span-2"><span>Vorlagenschlüssel des Pakets (kommagetrennt)</span><input class="workflow-action-templates" value="${esc((action.templateKeys || []).join(', '))}" placeholder="KONDOLENZLISTE_DECKBLATT, KONDOLENZLISTE_LISTE"></label>
				<label data-action-field="sourceStatus"><span>Aufgabenstatus danach</span><select class="workflow-action-source-status"><option value="">unverändert</option>${['OFFEN', 'IN_BEARBEITUNG', 'ERLEDIGT'].map((value) => `<option ${value === (action.sourceStatusAfter || '') ? 'selected' : ''}>${value}</option>`).join('')}</select></label>
				<label data-action-field="caseStatus"><span>Fallstatus danach</span><select class="workflow-action-case-status"><option value="">unverändert</option>${['NEU', 'IN_BEARBEITUNG', 'ABGESCHLOSSEN', 'STORNIERT'].map((value) => `<option ${value === (action.caseStatusAfter || '') ? 'selected' : ''}>${value}</option>`).join('')}</select></label>
				<label data-action-field="recipientCategory"><span>Empfänger-Kontaktgruppe</span><input class="workflow-action-recipient-category" value="${esc(action.recipientCategory || '')}" placeholder="z. B. Standesämter"></label>
			</div></details></td>
			<td><label class="bp-inline-check"><input class="workflow-action-repeatable" type="checkbox" ${action.repeatable ? 'checked' : ''}> Mehrfach</label></td>
			<td><button type="button" class="bp-danger remove-workflow-action">Löschen</button></td>
		</tr>`).join('')
	}

	function workflowEditor(workflow) {
		return `<form id="workflow-maintenance-form" data-workflow-editor="${Number(workflow.id)}" class="bp-workflow-editor"><div class="bp-panel-head"><div><p class="bp-eyebrow">${workflow.id ? esc(workflow.key) : 'Neuer Workflow'}</p><h3>${esc(workflow.name || 'Workflow anlegen')}</h3><p class="bp-muted">Platzhalter: {{source.title}}, {{case.number}}, {{case.first_name}}, {{case.last_name}}</p></div><label class="bp-inline-check"><input name="active" type="checkbox" ${workflow.active ? 'checked' : ''}> Aktiv</label></div><div class="bp-workflow-header">
			<label><span>Technischer Schlüssel</span><input name="key" value="${esc(workflow.key)}" pattern="[A-Za-z0-9_-]+" ${workflow.id ? 'readonly' : 'required'}></label><label><span>Bezeichnung</span><input name="name" value="${esc(workflow.name)}" required></label><label class="bp-span-2"><span>Beschreibung</span><textarea name="description" rows="3">${esc(workflow.description || '')}</textarea></label>
			<label><span>Ausgangstyp</span><select name="triggerType"><option value="TASK" ${workflow.triggerType !== 'SCHEDULE' ? 'selected' : ''}>Aufgabe</option><option value="SCHEDULE" ${workflow.triggerType === 'SCHEDULE' ? 'selected' : ''}>Termin</option></select></label><label><span>Auslösung</span><select name="triggerEvent"><option value="MANUAL" ${workflow.triggerEvent !== 'CONFIRMED' ? 'selected' : ''}>Manuell</option><option value="CONFIRMED" ${workflow.triggerEvent === 'CONFIRMED' ? 'selected' : ''}>Bei Terminbestätigung</option></select></label><label class="bp-span-2"><span>Terminvorlagen (kommagetrennte Schlüssel)</span><input name="schedulePresetKeys" value="${esc((workflow.triggerConfig?.schedulePresetKeys || []).join(', '))}" placeholder="TRAUERFEIER_1, TRAUERFEIER_2"></label>
			<label><span>Aufgabentitel enthält</span><input name="taskTitlePattern" value="${esc(workflow.taskTitlePattern || '')}" placeholder="leer = beliebig"></label><label><span>Checkliste</span><select name="checklistKey"><option value="">beliebig</option>${state.checklists.map((entry) => `<option value="${esc(entry.key)}" ${entry.key === workflow.checklistKey ? 'selected' : ''}>${esc(entry.name)}</option>`).join('')}</select></label><label><span>Erforderlicher Status</span><select name="requiredStatus">${[['ANY', 'beliebig'], ['OFFEN', 'Offen'], ['IN_BEARBEITUNG', 'In Bearbeitung'], ['ERLEDIGT', 'Erledigt']].map(([value, label]) => `<option value="${value}" ${value === workflow.requiredStatus ? 'selected' : ''}>${label}</option>`).join('')}</select></label>
		</div><section class="bp-workflow-actions-editor"><div class="bp-panel-head"><div><h4>Folgeaktionen</h4><p class="bp-muted">Reihenfolge am Griff ändern; „Inhalt und Logik“ öffnet alle fachlichen Felder der Aktion.</p></div><button type="button" class="bp-secondary" id="add-workflow-action">+ Neue Zeile</button></div><div class="bp-table-scroll"><table class="bp-value-table bp-workflow-maintenance"><thead><tr><th>Reihenfolge</th><th>Aktionsschlüssel</th><th>Typ</th><th>Schaltflächen-Text</th><th>Inhalt / Logik</th><th>Wiederholung</th><th>Aktion</th></tr></thead><tbody id="workflow-action-rows">${workflowActionRows(workflow.actions || [])}</tbody></table></div></section><p class="bp-save-state" id="workflow-form-state" aria-live="polite"></p><div class="bp-row-actions"><button class="bp-primary" id="save-workflow">Workflow speichern</button>${workflow.id ? `<button type="button" class="bp-danger delete-workflow" data-workflow-id="${workflow.id}">Workflow löschen</button>` : '<button type="button" class="bp-secondary cancel-new-workflow">Neuanlage verwerfen</button>'}</div></form>`
	}

	function showWorkflowForm(item = null) {
		if (item) {
			state.workflowAdminId = Number(item.id)
		} else {
			state.workflowAdmin = state.workflowAdmin.filter((entry) => Number(entry.id) !== 0)
			state.workflowAdmin.unshift({ id: 0, key: '', name: '', description: '', triggerType: 'TASK', triggerEvent: 'MANUAL', triggerConfig: { schedulePresetKeys: [] }, taskTitlePattern: '', checklistKey: '', requiredStatus: 'ANY', active: true, sortOrder: (state.workflowAdmin.length + 1) * 10, actions: [{ key: 'FOLGEAUFGABE', type: 'TASK', label: 'Folgeaufgabe anlegen', title: '', description: '', dueOffsetDays: 1, priority: 'NORMAL', sourceStatusAfter: 'IN_BEARBEITUNG' }] })
			state.workflowAdminId = 0
		}
		globalThis.localStorage?.setItem('bestatter:workflow-admin-id', String(state.workflowAdminId))
		render()
	}

	function dragControls(kind, index, label) {
		return `<span class="bp-order-cell"><button type="button" class="bp-drag-handle" draggable="true" data-drag-kind="${kind}" aria-label="${esc(label)} verschieben" title="Ziehen oder Alt+Pfeiltaste verwenden">⋮⋮</button><span class="bp-position-number">${index + 1}</span></span>`
	}

	function valueRow(item, index, technicalValuesLocked = false, variantItems = null) {
		const isVariant = Array.isArray(variantItems)
		const parent = isVariant ? variantItems.find((entry) => Number(entry.id) === Number(item.parentItemId)) : null
		const variantFields = isVariant ? `<td><select data-value-parent aria-label="Übergeordnete Variante, Zeile ${index + 1}"><option value="">Oberste Ebene</option>${variantItems.filter((entry) => Number(entry.id) !== Number(item.id)).map((entry) => `<option value="${esc(entry.value)}" ${entry.value === parent?.value ? 'selected' : ''}>${esc(entry.label)} (${esc(entry.value)})</option>`).join('')}</select></td><td><select data-value-scope aria-label="Bestattungszuordnung, Zeile ${index + 1}"><option value="" ${!item.metadata?.funeralScope ? 'selected' : ''}>Fachlich offen</option><option value="CREMATION" ${item.metadata?.funeralScope === 'CREMATION' ? 'selected' : ''}>Feuer-/Urnenbestattung</option><option value="BURIAL" ${item.metadata?.funeralScope === 'BURIAL' ? 'selected' : ''}>Erdbestattung</option></select></td>` : ''
		return `<tr data-value-row="${item.id}" draggable="false"><td class="bp-value-position">${dragControls('value', index, item.label)}</td><td><input data-value-value value="${esc(item.value)}" aria-label="Technischer Wert, Zeile ${index + 1}" ${technicalValuesLocked && item.id ? 'readonly' : ''}></td><td><input data-value-label value="${esc(item.label)}" aria-label="Bezeichnung, Zeile ${index + 1}"></td>${variantFields}<td><span class="bp-row-save-state" aria-live="polite"></span></td><td class="bp-value-actions"><button type="button" class="bp-secondary save-value">Speichern</button><button type="button" class="bp-danger delete-value" ${technicalValuesLocked && !isVariant ? 'disabled title="Verbindlicher Systemwert"' : ''}>Löschen</button></td></tr>`
	}

	function checklistItemRow(item, index) {
		return `<tr data-checklist-row="${Number(item.id || 0)}"><td class="bp-value-position">${dragControls('checklist', index, item.title || 'Neue Aufgabe')}</td><td><input data-checklist-title value="${esc(item.title || '')}" aria-label="Aufgabe, Zeile ${index + 1}" required></td><td><input data-checklist-description value="${esc(item.description || '')}" aria-label="Beschreibung, Zeile ${index + 1}"></td><td><input data-checklist-offset type="number" min="-365" max="365" step="1" value="${Number(item.dueOffsetDays || 0)}" aria-label="Fristversatz in Tagen, Zeile ${index + 1}"></td><td><select data-checklist-priority aria-label="Priorität, Zeile ${index + 1}">${[['HOCH','Hoch'],['NORMAL','Normal'],['NIEDRIG','Niedrig']].map(([value,label]) => `<option value="${value}" ${value === (item.priority || 'NORMAL') ? 'selected' : ''}>${label}</option>`).join('')}</select></td><td><button type="button" class="bp-danger delete-checklist-item">Löschen</button></td></tr>`
	}

	function schedulingView() {
		const requirementFields=(item)=>`<details class="bp-schedule-requirements"><summary>Pflichtbedarf festlegen</summary><div class="bp-form-grid"><label><span>Mitarbeitende</span><input data-required-staff type="number" min="0" value="${Number(item.requiredStaff||0)}"></label><label><span>Fahrzeuge</span><input data-required-vehicles type="number" min="0" value="${Number(item.requiredVehicles||0)}"></label><label><span>Räume</span><input data-required-rooms type="number" min="0" value="${Number(item.requiredRooms||0)}"></label><label><span>Kapellen</span><input data-required-chapels type="number" min="0" value="${Number(item.requiredChapels||0)}"></label><label><span>Ausstattung</span><input data-required-equipment type="number" min="0" value="${Number(item.requiredEquipment||0)}"></label></div><fieldset class="bp-member-picker"><legend>Standardmäßig vorbelegen</legend>${(state.scheduling?.resources||[]).filter((resource)=>resource.resourceType!=='STAFF'&&resource.active).map((resource)=>`<label class="bp-inline-check"><input data-default-resource type="checkbox" value="${esc(resource.key)}" ${(item.defaultResourceKeys||[]).includes(resource.key)?'checked':''}> ${esc(resource.name)}</label>`).join('')||'<small>Noch keine betrieblichen Ressourcen vorhanden.</small>'}</fieldset></details>`
		const typeRow=(item,newRow=false)=>`<tr data-schedule-type="${Number(item.id||0)}"><td><input data-key value="${esc(item.key||'')}" ${newRow?'placeholder="TRAUERFEIER"':'readonly'}></td><td><input data-name value="${esc(item.name||'')}"></td><td><select data-kind><option value="EXTERNAL_APPOINTMENT" ${item.scheduleKind!=='INTERNAL_ACTIVITY'?'selected':''}>Externer Fixtermin</option><option value="INTERNAL_ACTIVITY" ${item.scheduleKind==='INTERNAL_ACTIVITY'?'selected':''}>Interne Tätigkeit</option></select></td><td><input data-duration type="number" min="15" step="15" value="${Number(item.durationMinutes||60)}"></td><td><input data-before type="number" min="0" step="5" value="${Number(item.bufferBeforeMinutes||0)}"></td><td><input data-after type="number" min="0" step="5" value="${Number(item.bufferAfterMinutes||0)}"></td><td>${requirementFields(item)}</td><td><label class="bp-inline-check"><input data-active type="checkbox" ${item.active!==false?'checked':''}> Aktiv</label></td><td><button type="button" class="bp-secondary save-schedule-type">Speichern</button></td></tr>`
		const typeRows=(state.scheduling?.types||[]).map((item)=>typeRow(item)).join('');
		const resourceRows=(state.scheduling?.resources||[]).map((item)=>`<tr data-schedule-resource="${item.id}"><td><input data-key value="${esc(item.key)}" readonly></td><td><input data-name value="${esc(item.name)}"></td><td><select data-type>${[['STAFF','Mitarbeiter'],['VEHICLE','Fahrzeug'],['ROOM','Raum'],['CHAPEL','Kapelle'],['EQUIPMENT','Ausstattung']].map(([value,label])=>`<option value="${value}" ${item.resourceType===value?'selected':''}>${label}</option>`).join('')}</select></td><td><input data-uid value="${esc(item.linkedUid||'')}" placeholder="optional"></td><td><label class="bp-inline-check"><input data-conflict type="checkbox" ${item.conflictRelevant?'checked':''}> Konflikt prüfen</label></td><td><label class="bp-inline-check"><input data-active type="checkbox" ${item.active?'checked':''}> Aktiv</label></td><td><button type="button" class="bp-secondary save-schedule-resource">Speichern</button></td></tr>`).join('');
		return `<section class="bp-panel bp-custom-table"><div class="bp-panel-head"><div><h3>Terminplanung und Disposition</h3><p class="bp-muted">Terminarten definieren Dauer, Puffer und den mindestens zu disponierenden Bedarf. Konkrete Standardressourcen können vorbelegt werden; der Server verhindert unvollständige oder kollidierende Dispositionen.</p></div></div><section class="bp-field-section"><div class="bp-panel-head"><h4>Terminarten</h4><button type="button" class="bp-secondary" id="new-schedule-type">+ Terminart</button></div><div class="bp-table-scroll"><table><thead><tr><th>Schlüssel</th><th>Bezeichnung</th><th>Einordnung</th><th>Dauer</th><th>Puffer davor</th><th>Puffer danach</th><th>Personal und Ressourcen</th><th>Status</th><th></th></tr></thead><tbody id="schedule-type-rows">${typeRows}</tbody></table></div></section><section class="bp-field-section"><div class="bp-panel-head"><h4>Ressourcen</h4><button type="button" class="bp-secondary" id="new-schedule-resource">+ Ressource</button></div><p class="bp-muted">Kapellen werden getrennt von allgemeinen Räumen geführt. Persönliche Arbeits- und Abwesenheitszeiten sollen künftig aus Nextcloud Calendar übernommen werden; betriebliche Ressourcen bleiben hier gepflegt.</p><div class="bp-table-scroll"><table><thead><tr><th>Schlüssel</th><th>Bezeichnung</th><th>Typ</th><th>Nextcloud-UID</th><th>Prüfung</th><th>Status</th><th></th></tr></thead><tbody id="schedule-resource-rows">${resourceRows}</tbody></table></div></section></section>`
	}

	function surchargeView() {
		const articles = (state.articles || []).filter((item) => item.active && item.itemType !== 'PACKAGE')
		const row = (item = {}, isNew = false) => `<tr data-surcharge-rule="${Number(item.id || 0)}"><td><input data-rule-key value="${esc(item.ruleKey || '')}" ${isNew ? 'placeholder="NEUER_ZUSCHLAG" required' : 'readonly'}></td><td><input data-label value="${esc(item.label || '')}" required></td><td><select data-dimension>${[['PICKUP','Abholzeit'],['HEIGHT_CM','Größe (cm)'],['WEIGHT_KG','Gewicht (kg)'],['OTHER','Weitere']].map(([key,label])=>`<option value="${key}" ${key===item.dimension?'selected':''}>${label}</option>`).join('')}</select></td><td><input data-from type="number" min="0" step="1" value="${item.thresholdFrom ?? ''}" aria-label="Staffel von"></td><td><input data-to type="number" min="0" step="1" value="${item.thresholdTo ?? ''}" aria-label="Staffel bis"></td><td><select data-article><option value="">Noch keine Katalogleistung</option>${articles.map((article)=>`<option value="${Number(article.id)}" ${Number(article.id)===Number(item.articleId)?'selected':''}>${esc(article.articleNumber)} · ${esc(article.shortName)} · ${Number(article.salesPriceCents || 0) / 100} €</option>`).join('')}</select></td><td><label class="bp-inline-check"><input data-active type="checkbox" ${item.active?'checked':''}> Aktiv</label></td><td><input data-sort type="number" min="0" value="${Number(item.sortOrder || 0)}" aria-label="Sortierung"></td><td><button type="button" class="bp-secondary save-surcharge-rule">Speichern</button></td></tr>`
		return `<section class="bp-panel bp-custom-table"><div class="bp-panel-head"><div><h3>Zuschlagsstaffeln</h3><p class="bp-muted">Staffeln und feste Katalogleistungen pflegen. Die Abholzeit-, Größen- und Gewichtswerte können bereits im Fall erfasst werden. Eine automatische Ermittlung oder Übernahme in den Auftrag findet noch nicht statt. Änderungen nach Beauftragung erfolgen nur über den Nachtragsprozess.</p></div><button type="button" class="bp-primary" id="new-surcharge-rule">+ Staffel</button></div><div class="bp-table-scroll"><table><thead><tr><th>Schlüssel</th><th>Bezeichnung</th><th>Merkmal</th><th>Von</th><th>Bis</th><th>Katalogleistung / Preis</th><th>Status</th><th>Sortierung</th><th>Aktion</th></tr></thead><tbody id="surcharge-rule-rows">${(state.surchargeRules || []).map((item)=>row(item)).join('')}</tbody></table></div><template id="new-surcharge-template">${row({},true)}</template></section>`
	}

	function burialRuleView() {
		const variants = state.customizing.find((item) => item.key === 'BURIAL_VARIANT')?.items || []
		const articles = (state.articles || []).filter((item) => item.active && item.itemType !== 'PACKAGE')
		const articleOptions = (selected) => `<option value="">– keine –</option>${articles.map((article) => `<option value="${Number(article.id)}" ${Number(selected)===Number(article.id)?'selected':''}>${esc(article.articleNumber)} · ${esc(article.shortName)}</option>`).join('')}`
		const row = (item = {}, isNew = false) => `<tr data-burial-rule="${Number(item.id || 0)}"><td><select data-variant><option value="">Variante wählen</option>${variants.map((variant)=>`<option value="${esc(variant.value)}" ${variant.value===item.variantCode?'selected':''}>${esc(variant.label)} (${esc(variant.value)})</option>`).join('')}</select></td><td><select data-type>${[['MANDATORY_ARTICLE_GROUP','Gruppe erforderlich'],['MANDATORY_ARTICLE_GROUP_WITH_DEFAULT','Gruppe mit Standardartikel'],['SUGGESTED_ARTICLE','Artikel vorschlagen'],['EXCLUDED_ARTICLE_GROUP','Gruppe ausgeschlossen']].map(([key,label])=>`<option value="${key}" ${key===(item.ruleType||'MANDATORY_ARTICLE_GROUP')?'selected':''}>${label}</option>`).join('')}</select></td><td><input data-group value="${esc(item.articleGroup || '')}" list="burial-rule-groups" placeholder="Artikelgruppe"></td><td><select data-article>${articleOptions(item.articleId)}</select></td><td><select data-default>${articleOptions(item.defaultArticleId)}</select></td><td><input data-note value="${esc(item.note || '')}" placeholder="Konkreter interner Hinweis"></td><td><label class="bp-inline-check"><input data-active type="checkbox" ${item.active?'checked':''}> Aktiv</label></td><td><input data-sort type="number" min="0" value="${Number(item.sortOrder || 0)}" aria-label="Sortierung"></td><td><button type="button" class="bp-secondary save-burial-rule">Speichern</button></td></tr>`
		const groups = [...new Set(articles.map((article) => article.articleGroup))]
		return `<section class="bp-panel bp-custom-table"><div class="bp-panel-head"><div><h3>Varianten- und Leistungsregeln</h3><p class="bp-muted">Pflege von Pflichtgruppen, Standards und Vorschlägen. Die Gruppe „Sarg“ enthält derzeit auch die Standardurne und darf nicht ungeprüft als Urnenpflicht konfiguriert werden. Ungeklärte Varianten können nicht aktiviert werden.</p></div><button type="button" class="bp-primary" id="new-burial-rule">+ Regel</button></div><datalist id="burial-rule-groups">${groups.map((group)=>`<option value="${esc(group)}"></option>`).join('')}</datalist><div class="bp-table-scroll"><table><thead><tr><th>Variante</th><th>Regel</th><th>Artikelgruppe</th><th>Artikel</th><th>Standardartikel</th><th>Interner Hinweis</th><th>Status</th><th>Sort.</th><th>Aktion</th></tr></thead><tbody id="burial-rule-rows">${(state.burialVariantRules || []).map((item)=>row(item)).join('')}</tbody></table></div><template id="new-burial-rule-template">${row({},true)}</template></section>`
	}

	function customizing() {
		const tabs = [['value-lists', 'Wertelisten'], ['burial-rules', 'Variantenregeln'], ['surcharges', 'Zuschlagsstaffeln'], ['checklists', 'Checklisten'], ['workflows', 'Workflows'], ['scheduling', 'Terminplanung'], ['documents', 'Dokumentvorlagen'], ['deregistration', 'Abmeldungen']]
		let body = ''
		if (state.customizingTab === 'value-lists') {
			const sortedLists = [...state.customizing].sort((a, b) => a.name.localeCompare(b.name, 'de', { sensitivity: 'base' }) || a.key.localeCompare(b.key))
			const activeKey = state.valueListKey && state.customizing.some((list) => list.key === state.valueListKey) ? state.valueListKey : (sortedLists[0]?.key || '')
			state.valueListKey = activeKey
			const activeList = state.customizing.find((list) => list.key === activeKey)
			const isVariant = activeKey === 'BURIAL_VARIANT'
			const rows = (activeList?.items || []).map((item, index) => valueRow(item, index, activeList?.technicalValuesLocked, isVariant ? activeList.items : null)).join('')
			body = `<section class="bp-panel bp-custom-table"><div class="bp-panel-head"><div><h3>Wertelisten</h3><p class="bp-muted">Wertelisten alphabetisch anzeigen; die fachliche Reihenfolge der Einträge bleibt separat pflegbar.</p></div><span class="bp-status">${state.customizing.length} Listen</span></div><div class="bp-value-list-workspace"><nav class="bp-value-list-nav" aria-label="Wertelisten">${sortedLists.map((list) => `<button type="button" class="${list.key === activeKey ? 'active' : ''}" data-value-list="${esc(list.key)}"><span>${esc(list.name)}</span><small>${Number(list.itemCount ?? list.items.length)} Einträge</small></button>`).join('')}</nav><div class="bp-value-list-editor"><div class="bp-panel-head"><div><p class="bp-eyebrow">${esc(activeList?.key || '')}</p><h3>${esc(activeList?.name || 'Keine Werteliste vorhanden')}</h3>${activeList?.technicalValuesLocked ? `<small>${isVariant ? 'Bestehende Schlüssel bleiben fest; neue Ober- und Untervarianten können hier angelegt werden.' : 'Technische Schlüssel sind verbindlich; Bezeichnungen und Reihenfolge bleiben pflegbar.'}</small>` : ''}</div><button type="button" class="bp-primary" id="add-value" ${activeList && (!activeList.technicalValuesLocked || isVariant) ? '' : 'disabled'}>+ Neue Zeile</button></div>${isVariant ? '<p class="bp-muted">Einträge ohne übergeordnete Variante sind Bestattungsarten; darunter liegen die Untervarianten. „Zuordnung“ steuert nur die Katalogfilterung. Baum- und Waldbestattung sind eigenständige Bestattungsarten.</p>' : ''}<div class="bp-table-scroll"><table class="bp-value-table"><thead><tr><th>Reihenfolge</th><th>Technischer Wert</th><th>Sprechende Bezeichnung</th>${isVariant ? '<th>Übergeordnete Variante</th><th>Zuordnung</th>' : ''}<th>Status</th><th>Aktionen</th></tr></thead><tbody id="value-list-rows">${rows || `<tr class="bp-value-empty"><td colspan="${isVariant ? 7 : 5}" class="bp-empty">Noch keine Einträge. Mit „Neue Zeile“ beginnen.</td></tr>`}</tbody></table></div><p class="bp-muted">${isVariant ? '„Fachlich offen“ verhindert aktive Leistungsregeln. Neue Untervarianten erscheinen nach dem Speichern in der Fallauswahl.' : ''} Ziehen: Griff festhalten und Zeile verschieben. Tastatur: Griff fokussieren und Alt+Pfeil auf/ab verwenden. Ungespeicherte neue Zeilen zuerst speichern.</p></div></div></section>`
		} else if (state.customizingTab === 'burial-rules') body = burialRuleView()
		else if (state.customizingTab === 'surcharges') body = surchargeView()
		else if (state.customizingTab === 'checklists') {
			const checklistKey = state.checklistAdminKey && state.checklistAdmin.some((item) => item.key === state.checklistAdminKey) ? state.checklistAdminKey : (state.checklistAdmin[0]?.key || '')
			state.checklistAdminKey = checklistKey
			const checklist = state.checklistAdmin.find((item) => item.key === checklistKey)
			const checklistRows = (checklist?.items || []).map((item, index) => checklistItemRow(item, index)).join('')
			body = `<section class="bp-panel bp-custom-table"><div class="bp-panel-head"><div><h3>Checklisten</h3><p class="bp-muted">Checklisten als tabellarische Pflegeansicht verwalten. Zeilen lassen sich ergänzen, ändern, löschen und per Drag-and-drop sortieren.</p></div><button class="bp-primary" id="add-checklist">+ Checkliste</button></div><div class="bp-value-list-workspace"><nav class="bp-value-list-nav" aria-label="Checklisten">${state.checklistAdmin.map((item) => `<button type="button" class="${item.key === checklistKey ? 'active' : ''}" data-checklist-select="${esc(item.key)}"><span>${esc(item.name)}</span><small>${item.items.length} Aufgaben</small></button>`).join('')}</nav><div class="bp-value-list-editor" data-checklist-editor="${esc(checklistKey)}">${checklist ? `<div class="bp-checklist-header"><label><span>Technischer Schlüssel</span><input value="${esc(checklist.key)}" readonly></label><label><span>Bezeichnung</span><input class="checklist-name" value="${esc(checklist.name)}" required></label><label class="bp-span-2"><span>Beschreibung</span><textarea class="checklist-description" rows="2">${esc(checklist.description || '')}</textarea></label><label class="bp-inline-check"><input class="checklist-active" type="checkbox" ${checklist.active ? 'checked' : ''}> Aktiv</label></div><div class="bp-panel-head"><h4>Aufgaben der Checkliste</h4><button type="button" class="bp-secondary" id="add-checklist-item">+ Neue Zeile</button></div><div class="bp-table-scroll"><table class="bp-value-table bp-checklist-maintenance"><thead><tr><th>Reihenfolge</th><th>Aufgabe</th><th>Beschreibung</th><th>Frist + Tage</th><th>Priorität</th><th>Aktion</th></tr></thead><tbody id="checklist-item-rows">${checklistRows || '<tr class="bp-checklist-empty"><td colspan="6" class="bp-empty">Noch keine Aufgaben vorhanden.</td></tr>'}</tbody></table></div><p class="bp-save-state" id="checklist-save-state" aria-live="polite"></p><div class="bp-row-actions"><button class="bp-primary save-checklist" data-key="${esc(checklist.key)}">Checkliste speichern</button><button class="bp-danger delete-checklist" data-key="${esc(checklist.key)}">Checkliste löschen</button></div>` : '<p class="bp-empty">Noch keine Checkliste vorhanden.</p>'}</div></div></section>`
		} else if (state.customizingTab === 'workflows') {
			body = workflowAdminView()
		} else if (state.customizingTab === 'scheduling') body = schedulingView()
		else if (state.customizingTab === 'documents') body = documentTemplatesView()
		else if (state.customizingTab === 'deregistration') body = deregistrationTemplatesView()
		return `<div class="bp-page-head"><div><p class="bp-eyebrow">Administration</p><h2>Customizing</h2></div></div><div class="bp-subtabs">${tabs.map((tab) => `<button class="${state.customizingTab === tab[0] ? 'active' : ''}" data-customizing-tab="${tab[0]}">${tab[1]}</button>`).join('')}</div>${body}`
	}

	function bindCustomizing() {
		bindScheduling()
		const bindBurialRule = (row) => row.querySelector('.save-burial-rule')?.addEventListener('click', async () => {
			const id = Number(row.dataset.burialRule || 0)
			const rule = { variantCode: row.querySelector('[data-variant]').value, ruleType: row.querySelector('[data-type]').value, articleGroup: row.querySelector('[data-group]').value.trim(), articleId: row.querySelector('[data-article]').value, defaultArticleId: row.querySelector('[data-default]').value, note: row.querySelector('[data-note]').value.trim(), active: row.querySelector('[data-active]').checked, sortOrder: row.querySelector('[data-sort]').value }
			const button = row.querySelector('.save-burial-rule'); button.disabled = true
			try { await api(`${apiBase}/customizing/burial-rules${id ? `/${id}` : ''}`, { method: id ? 'PUT' : 'POST', body: new URLSearchParams({rule: JSON.stringify(rule)}) }); state.burialVariantRules = await api(`${apiBase}/customizing/burial-rules`); render(); notifySuccess('Variantenregel gespeichert.') }
			catch (error) { notifyError(error.message); button.disabled = false }
		})
		root.querySelectorAll('[data-burial-rule]').forEach(bindBurialRule)
		document.getElementById('new-burial-rule')?.addEventListener('click', () => { const row = document.getElementById('new-burial-rule-template').content.firstElementChild.cloneNode(true); document.getElementById('burial-rule-rows').append(row); bindBurialRule(row); row.querySelector('[data-variant]').focus() })
		const bindSurchargeRow = (row) => row.querySelector('.save-surcharge-rule')?.addEventListener('click', async () => {
			const id = Number(row.dataset.surchargeRule || 0)
			const rule = { ruleKey: row.querySelector('[data-rule-key]').value.trim(), label: row.querySelector('[data-label]').value.trim(), dimension: row.querySelector('[data-dimension]').value, thresholdFrom: row.querySelector('[data-from]').value, thresholdTo: row.querySelector('[data-to]').value, articleId: row.querySelector('[data-article]').value, active: row.querySelector('[data-active]').checked, sortOrder: row.querySelector('[data-sort]').value }
			const button = row.querySelector('.save-surcharge-rule'); button.disabled = true
			try { await api(`${apiBase}/customizing/surcharges${id ? `/${id}` : ''}`, { method: id ? 'PUT' : 'POST', body: new URLSearchParams({rule: JSON.stringify(rule)}) }); state.surchargeRules = await api(`${apiBase}/customizing/surcharges`); render(); notifySuccess('Zuschlagsstaffel gespeichert.') }
			catch (error) { notifyError(error.message); button.disabled = false }
		})
		root.querySelectorAll('[data-surcharge-rule]').forEach(bindSurchargeRow)
		document.getElementById('new-surcharge-rule')?.addEventListener('click', () => { const tbody = document.getElementById('surcharge-rule-rows'); const template = document.getElementById('new-surcharge-template'); const row = template.content.firstElementChild.cloneNode(true); tbody.append(row); bindSurchargeRow(row); row.querySelector('[data-rule-key]').focus() })
		document.getElementById('add-checklist')?.addEventListener('click', async () => {
			const key = await promptAction('Legen Sie einen eindeutigen technischen Schlüssel fest.', '', { title: 'Checkliste anlegen', label: 'Technischer Schlüssel, z. B. erstbestattung' })
			if (!key) return
			const name = await promptAction('Wie soll die Checkliste in der Anwendung heißen?', '', { title: 'Checkliste anlegen', label: 'Name der Checkliste' })
			if (!name) return
			await api(checklistUrl(), { method: 'POST', body: new URLSearchParams({ key, name }) })
			state.checklistAdmin = await api(checklistManageUrl())
			state.checklists = await api(checklistUrl())
			state.checklistAdminKey = key.toLowerCase().trim()
			globalThis.localStorage?.setItem('bestatter:checklist-admin-key', state.checklistAdminKey)
			render()
		})
		root.querySelectorAll('.delete-checklist').forEach((button) => button.addEventListener('click', async () => { if (!await confirmAction('Checkliste wirklich löschen?', { title: 'Checkliste löschen', confirmLabel: 'Löschen', danger: true })) return; await api(`${checklistUrl()}/${encodeURIComponent(button.dataset.key)}`, { method: 'DELETE' }); state.checklistAdmin = await api(checklistManageUrl()); state.checklists = await api(checklistUrl()); render() }))
		root.querySelectorAll('[data-value-list]').forEach((button) => button.addEventListener('click', () => { state.valueListKey = button.dataset.valueList; globalThis.localStorage?.setItem('bestatter:value-list-key', state.valueListKey); render() }))
		root.querySelectorAll('[data-checklist-select]').forEach((button) => button.addEventListener('click', async () => { if(root.querySelector('[data-checklist-editor].is-dirty')&&!await confirmAction('Ungespeicherte Änderungen verwerfen und eine andere Checkliste öffnen?',{title:'Checkliste wechseln',confirmLabel:'Verwerfen',danger:true}))return; state.checklistAdminKey = button.dataset.checklistSelect; globalThis.localStorage?.setItem('bestatter:checklist-admin-key', state.checklistAdminKey); render() }))
		const updateLocalItem = (saved) => { const list = state.customizing.find((entry) => entry.key === state.valueListKey); if (!list) return; const existing = list.items.find((entry) => Number(entry.id) === Number(saved.id)); if (existing) Object.assign(existing, saved); else list.items.push(saved); list.itemCount = list.items.length }
		const refreshPositions = (tbody, rowSelector) => [...tbody.querySelectorAll(rowSelector)].forEach((row, index) => { const number=row.querySelector('.bp-position-number'); if(number) number.textContent=String(index+1) })
		const bindSortableRows = (tbody, rowSelector, kind, saveOrder) => {
			if (!tbody) return
			tbody.querySelectorAll(`[data-drag-kind="${kind}"]`).forEach((handle) => {
				if (handle.dataset.sortableBound === 'true') return
				handle.dataset.sortableBound = 'true'
				handle.addEventListener('dragstart', (event) => { const dragged=handle.closest(rowSelector); tbody._bpDraggedRow=dragged; dragged?.classList.add('is-dragging'); event.dataTransfer.effectAllowed='move'; event.dataTransfer.setData('text/plain', dragged?.dataset.valueRow || dragged?.dataset.checklistRow || '') })
				handle.addEventListener('dragend', () => { tbody._bpDraggedRow?.classList.remove('is-dragging'); tbody.querySelectorAll('.is-drag-target').forEach((row)=>row.classList.remove('is-drag-target')); tbody._bpDraggedRow=null })
				handle.addEventListener('keydown', async (event) => { if(!event.altKey || !['ArrowUp','ArrowDown'].includes(event.key)) return; event.preventDefault(); const row=handle.closest(rowSelector); const sibling=event.key==='ArrowUp'?row.previousElementSibling:row.nextElementSibling; if(!sibling?.matches(rowSelector)) return; if(event.key==='ArrowUp') tbody.insertBefore(row,sibling); else tbody.insertBefore(sibling,row); refreshPositions(tbody,rowSelector); await saveOrder(); handle.focus() })
			})
			if (tbody.dataset.sortableBound !== kind) {
				tbody.dataset.sortableBound = kind
				tbody.addEventListener('dragover', (event) => { const dragged=tbody._bpDraggedRow; const target=event.target.closest(rowSelector); if(!dragged||!target||target===dragged) return; event.preventDefault(); target.classList.add('is-drag-target'); event.dataTransfer.dropEffect='move' })
				tbody.addEventListener('dragleave', (event) => event.target.closest(rowSelector)?.classList.remove('is-drag-target'))
				tbody.addEventListener('drop', async (event) => { const dragged=tbody._bpDraggedRow; const target=event.target.closest(rowSelector); if(!dragged||!target||target===dragged) return; event.preventDefault(); const after=event.clientY>target.getBoundingClientRect().top+target.getBoundingClientRect().height/2; tbody.insertBefore(dragged,after?target.nextSibling:target); target.classList.remove('is-drag-target'); refreshPositions(tbody,rowSelector); await saveOrder() })
			}
		}
		const bindValueRow = (row) => {
			const stateLabel = row.querySelector('.bp-row-save-state')
			const markDirty = () => { row.classList.add('is-dirty'); stateLabel.textContent = 'Ungespeichert'; stateLabel.dataset.state = 'dirty' }
			row.querySelectorAll('input,select').forEach((input) => input.addEventListener('input', markDirty))
			row.querySelector('[data-value-parent]')?.addEventListener('change', (event) => { const parent = state.customizing.find((list) => list.key === 'BURIAL_VARIANT')?.items.find((item) => item.value === event.target.value); if (parent?.metadata?.funeralScope) row.querySelector('[data-value-scope]').value = parent.metadata.funeralScope; markDirty() })
			row.querySelector('.save-value')?.addEventListener('click', async () => {
				const value = row.querySelector('[data-value-value]').value.trim(); const label = row.querySelector('[data-value-label]').value.trim()
				if (!value || !label) { stateLabel.textContent = 'Beide Felder ausfüllen'; stateLabel.dataset.state = 'error'; return }
				const id = Number(row.dataset.valueRow || 0); const button = row.querySelector('.save-value'); button.disabled = true; stateLabel.textContent = 'Speichert …'; stateLabel.dataset.state = 'saving'
				try { const params = { value, label }; if (state.valueListKey === 'BURIAL_VARIANT') { params.parentValue = row.querySelector('[data-value-parent]').value; params.funeralScope = row.querySelector('[data-value-scope]').value } const saved = await api(id ? `${urls.customizing}/item/${id}` : `${urls.customizing}/${encodeURIComponent(state.valueListKey)}`, { method: id ? 'PUT' : 'POST', feedback: false, body: new URLSearchParams(params) }); row.dataset.valueRow = saved.id; updateLocalItem(saved); row.classList.remove('is-dirty','is-new'); stateLabel.textContent = 'Gespeichert'; stateLabel.dataset.state = 'saved'; row.querySelector('.delete-value').disabled = false; if (state.valueListKey === 'BURIAL_VARIANT') { state.customizing = (await api(urls.customizing)).lists; render() } else bindSortableRows(document.getElementById('value-list-rows'),'[data-value-row]','value',saveValueOrder); notifySuccess(`„${saved.label}“ wurde gespeichert.`) } catch (error) { stateLabel.textContent = error.message; stateLabel.dataset.state = 'error' } finally { button.disabled = false }
			})
			row.querySelector('.delete-value')?.addEventListener('click', async () => {
				const id = Number(row.dataset.valueRow || 0); if (!id) { row.remove(); return }
				if (!await confirmAction('Diesen Wert wirklich aus der geöffneten Werteliste löschen?', { title: 'Listenwert löschen', confirmLabel: 'Löschen', danger: true })) return
				try { await api(`${urls.customizing}/item/${id}`, { method: 'DELETE', feedback: false }); const list=state.customizing.find((entry)=>entry.key===state.valueListKey); if(list){list.items=list.items.filter((entry)=>Number(entry.id)!==id);list.itemCount=list.items.length} if (state.valueListKey === 'BURIAL_VARIANT') { state.customizing = (await api(urls.customizing)).lists; render() } else { row.remove(); refreshPositions(document.getElementById('value-list-rows'),'[data-value-row]') } notifySuccess('Der Listenwert wurde gelöscht.') } catch(error) { stateLabel.textContent=error.message; stateLabel.dataset.state='error' }
			})
		}
		root.querySelectorAll('[data-value-row]').forEach(bindValueRow)
		const valueBody=document.getElementById('value-list-rows')
		const saveValueOrder=async()=>{ const rows=[...valueBody.querySelectorAll('[data-value-row]')]; const ids=rows.map((row)=>Number(row.dataset.valueRow||0)); if(ids.includes(0)){notifyError('Neue Zeilen bitte zuerst speichern; danach kann die Reihenfolge gespeichert werden.');return} const original=[...(state.customizing.find((entry)=>entry.key===state.valueListKey)?.items||[])]; try{const saved=await api(`${urls.customizing}/${encodeURIComponent(state.valueListKey)}/reorder`,{method:'PUT',feedback:false,body:new URLSearchParams({itemIds:JSON.stringify(ids)})});const list=state.customizing.find((entry)=>entry.key===state.valueListKey);if(list){list.items=saved;list.itemCount=saved.length}notifySuccess('Die Reihenfolge wurde gespeichert.')}catch(error){const list=state.customizing.find((entry)=>entry.key===state.valueListKey);if(list)list.items=original;render();notifyError(error.message)}}
		bindSortableRows(valueBody,'[data-value-row]','value',saveValueOrder)
		document.getElementById('add-value')?.addEventListener('click', () => { const tbody=document.getElementById('value-list-rows'); tbody.querySelector('.bp-value-empty')?.remove(); const position=tbody.querySelectorAll('[data-value-row]').length; const variants=state.valueListKey==='BURIAL_VARIANT' ? state.customizing.find((list)=>list.key==='BURIAL_VARIANT')?.items || [] : null; const template=document.createElement('template'); template.innerHTML=valueRow({id:0,value:'',label:''},position,state.valueListKey==='BURIAL_VARIANT',variants); const row=template.content.firstElementChild; tbody.append(row); row.classList.add('is-new','is-dirty'); row.querySelector('.bp-row-save-state').textContent='Neu · ungespeichert'; bindValueRow(row); row.querySelector('[data-value-value]').focus(); row.scrollIntoView({block:'nearest'}) })
		const checklistBody=document.getElementById('checklist-item-rows'); const markChecklistDirty=()=>{root.querySelector('[data-checklist-editor]')?.classList.add('is-dirty');const label=document.getElementById('checklist-save-state');if(label){label.textContent='Änderungen noch nicht gespeichert';label.dataset.state='dirty'}}
		bindSortableRows(checklistBody,'[data-checklist-row]','checklist',async()=>markChecklistDirty())
		checklistBody?.querySelectorAll('input,select').forEach((input)=>input.addEventListener('input',markChecklistDirty))
		root.querySelectorAll('.checklist-name,.checklist-description,.checklist-active').forEach((input)=>input.addEventListener('input',markChecklistDirty))
		root.querySelectorAll('.delete-checklist-item').forEach((button)=>button.addEventListener('click',()=>{button.closest('[data-checklist-row]').remove();refreshPositions(checklistBody,'[data-checklist-row]');markChecklistDirty()}))
		document.getElementById('add-checklist-item')?.addEventListener('click',()=>{checklistBody.querySelector('.bp-checklist-empty')?.remove();const position=checklistBody.querySelectorAll('[data-checklist-row]').length;checklistBody.insertAdjacentHTML('beforeend',checklistItemRow({id:0,title:'',description:'',priority:'NORMAL',dueOffsetDays:0},position));const row=checklistBody.lastElementChild;row.querySelectorAll('input,select').forEach((input)=>input.addEventListener('input',markChecklistDirty));row.querySelector('.delete-checklist-item').addEventListener('click',()=>{row.remove();refreshPositions(checklistBody,'[data-checklist-row]');markChecklistDirty()});bindSortableRows(checklistBody,'[data-checklist-row]','checklist',async()=>markChecklistDirty());markChecklistDirty();row.querySelector('[data-checklist-title]').focus();row.scrollIntoView({block:'nearest'})})
		root.querySelectorAll('.save-checklist').forEach((button) => button.addEventListener('click', async () => { const card=button.closest('[data-checklist-editor]'); const status=document.getElementById('checklist-save-state'); const items=[...card.querySelectorAll('[data-checklist-row]')].map((row)=>({id:Number(row.dataset.checklistRow||0),title:row.querySelector('[data-checklist-title]').value.trim(),description:row.querySelector('[data-checklist-description]').value.trim(),dueOffsetDays:Number(row.querySelector('[data-checklist-offset]').value||0),priority:row.querySelector('[data-checklist-priority]').value})); if(items.some((item)=>!item.title)){status.textContent='Jede Zeile benötigt eine Aufgabenbezeichnung.';status.dataset.state='error';return} button.disabled=true;status.textContent='Checkliste wird gespeichert …';status.dataset.state='saving';try{await api(`${checklistUrl()}/${encodeURIComponent(button.dataset.key)}`,{method:'PUT',feedback:false,body:new URLSearchParams({name:card.querySelector('.checklist-name').value,description:card.querySelector('.checklist-description').value,active:card.querySelector('.checklist-active').checked?'true':'false',items:JSON.stringify(items)})});[state.checklistAdmin,state.checklists]=await Promise.all([api(checklistManageUrl()),api(checklistUrl())]);render();notifySuccess('Die Checkliste wurde vollständig gespeichert.')}catch(error){status.textContent=error.message;status.dataset.state='error';button.disabled=false} }))
	}

	function bindScheduling(){
		const bindType=(row)=>row.querySelector('.save-schedule-type')?.addEventListener('click',async()=>{const id=Number(row.dataset.scheduleType||0);const number=(selector)=>Number(row.querySelector(selector)?.value||0);const data={key:row.querySelector('[data-key]').value.trim(),name:row.querySelector('[data-name]').value.trim(),scheduleKind:row.querySelector('[data-kind]').value,durationMinutes:number('[data-duration]'),bufferBeforeMinutes:number('[data-before]'),bufferAfterMinutes:number('[data-after]'),requiredStaff:number('[data-required-staff]'),requiredVehicles:number('[data-required-vehicles]'),requiredRooms:number('[data-required-rooms]'),requiredChapels:number('[data-required-chapels]'),requiredEquipment:number('[data-required-equipment]'),defaultResourceKeys:[...row.querySelectorAll('[data-default-resource]:checked')].map((input)=>input.value),active:row.querySelector('[data-active]').checked};try{await api(`${schedulingUrl()}/types/${id}`,{method:'PUT',body:new URLSearchParams({data:JSON.stringify(data)})});state.scheduling=await api(schedulingUrl());render();notifySuccess('Terminart einschließlich Ressourcenbedarf wurde gespeichert.')}catch(error){notifyError(error.message)}})
		const bindResource=(row)=>row.querySelector('.save-schedule-resource')?.addEventListener('click',async()=>{const id=Number(row.dataset.scheduleResource||0);const data={key:row.querySelector('[data-key]').value.trim(),name:row.querySelector('[data-name]').value.trim(),resourceType:row.querySelector('[data-type]').value,linkedUid:row.querySelector('[data-uid]').value.trim(),conflictRelevant:row.querySelector('[data-conflict]').checked,active:row.querySelector('[data-active]').checked};try{await api(`${schedulingUrl()}/resources/${id}`,{method:'PUT',body:new URLSearchParams({data:JSON.stringify(data)})});state.scheduling=await api(schedulingUrl());render();notifySuccess('Ressource wurde gespeichert.')}catch(error){notifyError(error.message)}})
		root.querySelectorAll('[data-schedule-type]').forEach(bindType);root.querySelectorAll('[data-schedule-resource]').forEach(bindResource)
		document.getElementById('new-schedule-type')?.addEventListener('click',()=>{const body=document.getElementById('schedule-type-rows');const defaults='<details class="bp-schedule-requirements"><summary>Pflichtbedarf festlegen</summary><div class="bp-form-grid">'+[['staff','Mitarbeitende'],['vehicles','Fahrzeuge'],['rooms','Räume'],['chapels','Kapellen'],['equipment','Ausstattung']].map(([key,label])=>`<label><span>${label}</span><input data-required-${key} type="number" min="0" value="0"></label>`).join('')+'</div></details>';body.insertAdjacentHTML('beforeend',`<tr data-schedule-type="0"><td><input data-key placeholder="TRAUERFEIER"></td><td><input data-name></td><td><select data-kind><option value="EXTERNAL_APPOINTMENT">Externer Fixtermin</option><option value="INTERNAL_ACTIVITY">Interne Tätigkeit</option></select></td><td><input data-duration type="number" min="15" step="15" value="60"></td><td><input data-before type="number" min="0" step="5" value="0"></td><td><input data-after type="number" min="0" step="5" value="0"></td><td>${defaults}</td><td><label class="bp-inline-check"><input data-active type="checkbox" checked> Aktiv</label></td><td><button type="button" class="bp-secondary save-schedule-type">Speichern</button></td></tr>`);const row=body.lastElementChild;bindType(row);row.querySelector('[data-key]').focus()})
		document.getElementById('new-schedule-resource')?.addEventListener('click',()=>{const body=document.getElementById('schedule-resource-rows');body.insertAdjacentHTML('beforeend','<tr data-schedule-resource="0"><td><input data-key placeholder="FAHRZEUG_1"></td><td><input data-name></td><td><select data-type><option value="STAFF">Mitarbeiter</option><option value="VEHICLE">Fahrzeug</option><option value="ROOM">Raum</option><option value="CHAPEL">Kapelle</option><option value="EQUIPMENT">Ausstattung</option></select></td><td><input data-uid placeholder="optional"></td><td><label class="bp-inline-check"><input data-conflict type="checkbox" checked> Konflikt prüfen</label></td><td><label class="bp-inline-check"><input data-active type="checkbox" checked> Aktiv</label></td><td><button type="button" class="bp-secondary save-schedule-resource">Speichern</button></td></tr>');const row=body.lastElementChild;bindResource(row);row.querySelector('[data-key]').focus()})
	}

	function bindConfigurationAdministration() {
		const showCardError = (card, error) => { const status = card.querySelector('.bp-card-state'); if (status) { status.textContent = error.message; status.dataset.state = 'error' } }
		const validateConfigurationKey = (card, label) => {
			const key = card.querySelector('[name="key"]')?.value.trim() || ''
			const name = card.querySelector('[name="name"]')?.value.trim() || ''
			if (key && name && /^[A-Za-z0-9_-]+$/.test(key)) return true
			showCardError(card, new Error(`${label} darf keine Leerzeichen enthalten; Schlüssel und Bezeichnung sind Pflichtfelder.`))
			return false
		}
		document.getElementById('new-branch')?.addEventListener('click', () => { state.branches = [{ id: 0, key: '', name: '', street: '', postalCode: '', city: '', country: 'Deutschland', countryCode: 'DE', federalState: '', invoiceProfile: 'ZUGFERD', paymentQrStandard: 'EPC069-12', phone: '', email: '', accountHolder: '', bankName: '', iban: '', bic: '', creditorId: '', paymentTermDays: 14, vatId: '', taxNumber: '', registerCourt: '', registerNumber: '', managingDirectors: '', electronicAddress: '', memberUids: [state.team.currentUid], active: true }, ...state.branches.filter((entry) => entry.id)]; render() })
		root.querySelectorAll('[name="countryCode"]').forEach((select) => select.addEventListener('change', () => { const card=select.closest('[data-branch-id]'); const profile=(state.countryProfiles||[]).find((item)=>item.countryCode===select.value); card.querySelector('.bp-federal-state')?.classList.toggle('bp-hidden',select.value!=='AT'); if(profile){card.querySelector('[name="country"]').value=profile.name;card.querySelector('[name="invoiceProfile"]').value=profile.invoiceProfile;card.querySelector('[name="paymentQrStandard"]').value=profile.paymentQrStandard} }))
		root.querySelectorAll('.save-country-profile').forEach((button) => button.addEventListener('click', async () => { const card=button.closest('[data-country-profile]'); const status=card.querySelector('.bp-card-state'); const values={vatRates:card.querySelector('[name="vatRates"]').value.split(/[,;]+/).map((value)=>value.trim()).filter(Boolean),invoiceProfile:card.querySelector('[name="invoiceProfile"]').value,paymentQrStandard:card.querySelector('[name="paymentQrStandard"]').value}; button.disabled=true; try { const saved=await api(`${apiBase}/country-profiles/${card.dataset.countryProfile}`,{method:'PUT',feedback:false,body:new URLSearchParams({profile:JSON.stringify(values)})}); state.countryProfiles=(state.countryProfiles||[]).map((item)=>item.countryCode===saved.countryCode?saved:item); const catalog=await api(articleUrl()); state.allowedVatRates=catalog.allowedVatRates||state.allowedVatRates; status.textContent='Länderprofil gespeichert.';status.dataset.state='saved';render();notifySuccess('Länderprofil und zulässige Steuersätze wurden gespeichert.') } catch(error){button.disabled=false;showCardError(card,error)} }))
		root.querySelectorAll('.save-branch').forEach((button) => button.addEventListener('click', async () => { const card = button.closest('[data-branch-id]'); if (!validateConfigurationKey(card, 'Der Niederlassungsschlüssel')) return; const value = (name) => card.querySelector(`[name="${name}"]`); const names = ['key','name','street','postalCode','city','country','countryCode','federalState','invoiceProfile','paymentQrStandard','phone','email','accountHolder','bankName','iban','bic','creditorId','paymentTermDays','vatId','taxNumber','registerCourt','registerNumber','managingDirectors','electronicAddress']; const data = Object.fromEntries(names.map((name) => [name, value(name).value])); data.memberUids = [...card.querySelectorAll('[name="memberUids"]:checked')].map((input) => input.value); data.active = value('active').checked; button.disabled = true; try { await api(`${branchUrl()}/${button.dataset.id}`, { method: 'PUT', feedback: false, body: new URLSearchParams({ branch: JSON.stringify(data) }) }); state.branches = await api(branchUrl()); render(); notifySuccess('Niederlassungs-, Länder-, Bank- und Unternehmensdaten wurden gespeichert.') } catch (error) { button.disabled = false; showCardError(card, error) } }))
		root.querySelectorAll('.save-branch-bank').forEach((button) => button.addEventListener('click', async () => { const card = button.closest('[data-branch-id]'); const value = (name) => card.querySelector(`[name="${name}"]`); const names = ['accountHolder','bankName','iban','bic','creditorId','paymentTermDays','vatId','taxNumber','registerCourt','registerNumber','managingDirectors','electronicAddress']; const bankData = Object.fromEntries(names.map((name) => [name, value(name).value])); button.disabled = true; try { const saved = await api(`${branchUrl()}/${button.dataset.id}/bank-data`, { method: 'PUT', feedback: false, body: new URLSearchParams({ bankData: JSON.stringify(bankData) }) }); state.branches = state.branches.map((entry) => entry.id === saved.id ? saved : entry); render(); notifySuccess('Bank- und Unternehmensdaten wurden gespeichert.') } catch (error) { button.disabled = false; showCardError(card, error) } }))
		document.getElementById('save-invoice-settings')?.addEventListener('click', async () => { const form = document.getElementById('invoice-settings'); const value = (name) => form.querySelector(`[name="${name}"]`); const data = { prefix: value('prefix').value, pattern: value('pattern').value, sequenceLength: Number(value('sequenceLength').value), sequenceScope: value('sequenceScope').value, caseReference: value('caseReference').checked, zugferdEnabled: value('zugferdEnabled').checked, xrechnungEnabled: value('xrechnungEnabled').checked, normativeValidationRequired: value('normativeValidationRequired').checked, qrEnabled: value('qrEnabled').checked }; try { state.invoiceSettings = await api(invoiceSettingsUrl(), { method: 'PUT', body: new URLSearchParams({ settings: JSON.stringify(data) }) }); render() } catch (error) { showCardError(form.closest('.bp-panel'), error) } })
		root.querySelectorAll('.delete-branch').forEach((button) => button.addEventListener('click', async () => { if (!await confirmAction('Niederlassung löschen?', { title: 'Niederlassung löschen', confirmLabel: 'Löschen', danger: true })) return; await api(`${apiBase}/configuration/branch/${button.dataset.id}`, { method: 'DELETE' }); state.branches = await api(branchUrl()); render() }))
		document.getElementById('provision-templates')?.addEventListener('click', async () => { const result = await api(`${documentTemplateUrl()}/provision`, { method: 'POST', feedback: false, loadingLabel: 'Fehlende Standardvorlagen werden ergänzt …' }); const files=result.files||[]; const created=files.filter((file)=>file.status==='CREATED').length; const preserved=files.filter((file)=>file.status==='PRESERVED').length; state.documentTemplateOptions=await api(documentTemplateOptionsUrl()); render(); notifySuccess(`${created} fehlende Standardvorlage${created===1?' wurde':'n wurden'} ergänzt; ${preserved} vorhandene individuelle Datei${preserved===1?' wurde':'en wurden'} unverändert beibehalten.`) })
		document.getElementById('download-template-fields')?.addEventListener('click', async () => { try { await download(`${apiBase}/template-fields.csv`, 'Bestatter-Dokumentvorlagen-Feldkatalog.csv') } catch (error) { notifyError(error.message) } })
		document.getElementById('new-document-template')?.addEventListener('click', () => { state.documentTemplates = [{ id: 0, key: '', name: '', category: 'Allgemein', fileName: '', outputSubfolder: '03 Behörden', requiredFields: [], description: '', supportsPdf: false, active: true, sortOrder: 100 }, ...state.documentTemplates.filter((entry) => entry.id)]; render() })
		root.querySelectorAll('.save-document-template').forEach((button) => button.addEventListener('click', async () => { const card = button.closest('[data-document-template]'); if (!validateConfigurationKey(card, 'Der Vorlagenschlüssel')) return; const value = (name) => card.querySelector(`[name="${name}"]`); const template = { key: value('key').value, name: value('name').value, category: value('category').value, fileName: value('fileName').value, outputSubfolder: value('outputSubfolder').value, sortOrder: Number(value('sortOrder').value || 0), requiredFields: value('requiredFields').value.split(',').map((entry) => entry.trim()).filter(Boolean), description: value('description').value, supportsPdf: value('supportsPdf').checked, active: value('active').checked }; try { await api(`${documentTemplateUrl()}/${button.dataset.id}`, { method: 'PUT', body: new URLSearchParams({ template: JSON.stringify(template) }) }); state.documentTemplates = await api(documentTemplateUrl()); render() } catch (error) { showCardError(card, error) } }))
		root.querySelectorAll('.duplicate-document-template').forEach((button) => button.addEventListener('click', async () => { const card=button.closest('[data-document-template]'); button.disabled=true; try { await api(`${documentTemplateUrl()}/${button.dataset.id}/duplicate`, {method:'POST'}); [state.documentTemplates,state.documentTemplateOptions]=await Promise.all([api(documentTemplateUrl()),api(documentTemplateOptionsUrl())]); render() } catch(error){ button.disabled=false; showCardError(card,error) } }))
		root.querySelectorAll('.preview-document-template').forEach((button) => button.addEventListener('click', () => { const card = button.closest('[data-document-template]'); const value = (name) => card.querySelector(`[name="${name}"]`)?.value || ''; showTextPreview(value('name') || 'Dokumentenvorlage', value('fileName'), `${value('description')}\n\nAblage: ${value('outputSubfolder')}\nPflichtangaben: ${value('requiredFields') || 'keine'}`) }))
		root.querySelectorAll('.delete-document-template').forEach((button) => button.addEventListener('click', async () => { if (!await confirmAction('Dokumentvorlage wirklich löschen?', { title: 'Dokumentvorlage löschen', confirmLabel: 'Löschen', danger: true })) return; await api(`${apiBase}/configuration/document/${button.dataset.id}`, { method: 'DELETE' }); state.documentTemplates = await api(documentTemplateUrl()); render() }))
		document.getElementById('new-dereg-template')?.addEventListener('click', () => { state.deregistrationTemplates = [{ id: 0, key: '', recipientType: '', name: '', contactCategory: '', deliveryChannels: ['POST'], formType: 'STANDARD', subjectTemplate: '', bodyTemplate: '', requiredFields: [], allowedStatuses: ['ENTWURF', 'VORBEREITET'], followUpDays: 0, documentTemplateKey: '', active: true }, ...state.deregistrationTemplates.filter((entry) => entry.id)]; render() })
		root.querySelectorAll('.save-dereg-template').forEach((button) => button.addEventListener('click', async () => { const card = button.closest('[data-dereg-template]'); if (!validateConfigurationKey(card, 'Der Vorgangsschlüssel')) return; const value = (name) => card.querySelector(`[name="${name}"]`); const template = { key: value('key').value, recipientType: value('recipientType').value || value('key').value, name: value('name').value, contactCategory: value('contactCategory').value, deliveryChannels: value('deliveryChannels').value.split(',').map((entry) => entry.trim()).filter(Boolean), formType: value('formType').value, subjectTemplate: value('subjectTemplate').value, bodyTemplate: value('bodyTemplate').value, requiredFields: value('requiredFields').value.split(',').map((entry) => entry.trim()).filter(Boolean), allowedStatuses: value('allowedStatuses').value.split(',').map((entry) => entry.trim()).filter(Boolean), followUpDays: Number(value('followUpDays').value || 0), documentTemplateKey: value('documentTemplateKey').value, active: value('active').checked }; try { await api(`${deregistrationTemplateUrl()}/${button.dataset.id}`, { method: 'PUT', body: new URLSearchParams({ template: JSON.stringify(template) }) }); state.deregistrationTemplates = await api(deregistrationTemplateUrl()); render() } catch (error) { showCardError(card, error) } }))
		root.querySelectorAll('.preview-dereg-template').forEach((button) => button.addEventListener('click', () => { const card = button.closest('[data-dereg-template]'); const value = (name) => card.querySelector(`[name="${name}"]`)?.value || ''; showTextPreview(value('name') || 'Abmeldung', value('subjectTemplate'), value('bodyTemplate')) }))
		root.querySelectorAll('.delete-dereg-template').forEach((button) => button.addEventListener('click', async () => { if (!await confirmAction('Abmeldevorgang wirklich löschen?', { title: 'Abmeldevorgang löschen', confirmLabel: 'Löschen', danger: true })) return; await api(`${apiBase}/configuration/deregistration/${button.dataset.id}`, { method: 'DELETE' }); state.deregistrationTemplates = await api(deregistrationTemplateUrl()); render() }))
	}

	function bindWorkflowAdmin() {
		document.getElementById('new-workflow')?.addEventListener('click', () => showWorkflowForm())
		const form = document.getElementById('workflow-maintenance-form')
		const markDirty = () => { if (!form) return; form.classList.add('is-dirty'); const status = document.getElementById('workflow-form-state'); if (status) { status.textContent = 'Änderungen noch nicht gespeichert'; status.dataset.state = 'dirty' } }
		root.querySelectorAll('[data-workflow-select]').forEach((button) => button.addEventListener('click', async () => {
			if (form?.classList.contains('is-dirty') && !await confirmAction('Ungespeicherte Änderungen verwerfen und einen anderen Workflow öffnen?', { title: 'Workflow wechseln', confirmLabel: 'Verwerfen', danger: true })) return
			state.workflowAdminId = Number(button.dataset.workflowSelect)
			globalThis.localStorage?.setItem('bestatter:workflow-admin-id', String(state.workflowAdminId))
			render()
		}))
		const actionRows = document.getElementById('workflow-action-rows')
		const refreshActionPositions = () => actionRows?.querySelectorAll('[data-workflow-action-row]').forEach((row, index) => { const label = row.querySelector('.bp-position-number'); if (label) label.textContent = String(index + 1) })
		const updateActionFields = (row) => { const type = row.querySelector('.workflow-action-type').value; const visible = { TASK: ['title','description','offset','priority','sourceStatus','caseStatus'], REMINDER: ['title','description','offset','priority','sourceStatus','caseStatus'], SCHEDULE: ['title','description','offset','priority','sourceStatus','caseStatus'], DOCUMENT: ['template','sourceStatus','caseStatus'], DOCUMENT_BUNDLE: ['templates','sourceStatus','caseStatus'], EMAIL_DRAFT: ['title','description','recipientCategory','sourceStatus','caseStatus'], CONTACT_ACTIVITY: ['title','description','sourceStatus','caseStatus'], CASE_STATUS: ['sourceStatus','caseStatus'] }[type] || []; row.querySelectorAll('[data-action-field]').forEach((field) => { field.hidden = !visible.includes(field.dataset.actionField) }) }
		const bindActionRow = (row) => {
			row.querySelectorAll('input,select,textarea').forEach((input) => input.addEventListener('input', markDirty))
			const type = row.querySelector('.workflow-action-type'); type.addEventListener('change', () => { updateActionFields(row); markDirty() }); updateActionFields(row)
			row.querySelector('.remove-workflow-action')?.addEventListener('click', () => { row.remove(); refreshActionPositions(); markDirty() })
			const handle = row.querySelector('[data-drag-kind="workflow-action"]')
			if (handle) {
				handle.addEventListener('dragstart', (event) => { actionRows._bpDraggedRow = row; row.classList.add('is-dragging'); event.dataTransfer.effectAllowed = 'move' })
				handle.addEventListener('dragend', () => { row.classList.remove('is-dragging'); actionRows.querySelectorAll('.is-drag-target').forEach((item) => item.classList.remove('is-drag-target')); actionRows._bpDraggedRow = null })
				handle.addEventListener('keydown', (event) => { if (!event.altKey || !['ArrowUp','ArrowDown'].includes(event.key)) return; event.preventDefault(); const sibling = event.key === 'ArrowUp' ? row.previousElementSibling : row.nextElementSibling; if (!sibling) return; actionRows.insertBefore(row, event.key === 'ArrowUp' ? sibling : sibling.nextElementSibling); refreshActionPositions(); markDirty(); handle.focus() })
			}
		}
		actionRows?.addEventListener('dragover', (event) => { const dragged = actionRows._bpDraggedRow; const target = event.target.closest('[data-workflow-action-row]'); if (!dragged || !target || target === dragged) return; event.preventDefault(); actionRows.querySelectorAll('.is-drag-target').forEach((row) => row.classList.remove('is-drag-target')); target.classList.add('is-drag-target') })
		actionRows?.addEventListener('drop', (event) => { const dragged = actionRows._bpDraggedRow; const target = event.target.closest('[data-workflow-action-row]'); if (!dragged || !target || target === dragged) return; event.preventDefault(); const after = event.clientY > target.getBoundingClientRect().top + target.getBoundingClientRect().height / 2; actionRows.insertBefore(dragged, after ? target.nextSibling : target); target.classList.remove('is-drag-target'); refreshActionPositions(); markDirty() })
		actionRows?.querySelectorAll('[data-workflow-action-row]').forEach(bindActionRow)
		document.getElementById('add-workflow-action')?.addEventListener('click', () => { const staging = document.createElement('table'); staging.innerHTML = `<tbody>${workflowActionRows([{ key: `ACTION_${Date.now()}`, type: 'TASK', label: 'Folgeaktion', title: '', description: '', dueOffsetDays: 1, priority: 'NORMAL' }])}</tbody>`; const row = staging.querySelector('[data-workflow-action-row]'); actionRows.append(row); bindActionRow(row); refreshActionPositions(); markDirty(); row.querySelector('.workflow-action-key').focus(); row.scrollIntoView({ block: 'nearest' }) })
		form?.querySelectorAll(':scope > .bp-workflow-header input, :scope > .bp-workflow-header select, :scope > .bp-workflow-header textarea, :scope > .bp-panel-head input').forEach((input) => input.addEventListener('input', markDirty))
		form?.addEventListener('submit', async (event) => {
			event.preventDefault(); const data = Object.fromEntries(new FormData(form)); const id = Number(form.dataset.workflowEditor || 0)
			const actions = [...form.querySelectorAll('[data-workflow-action-row]')].map((row) => ({ key: row.querySelector('.workflow-action-key').value.trim(), type: row.querySelector('.workflow-action-type').value, label: row.querySelector('.workflow-action-label').value.trim(), title: row.querySelector('.workflow-action-title').value, description: row.querySelector('.workflow-action-description').value, dueOffsetDays: Number(row.querySelector('.workflow-action-offset').value || 0), priority: row.querySelector('.workflow-action-priority').value, templateKey: row.querySelector('.workflow-action-template').value, templateKeys: row.querySelector('.workflow-action-templates').value.split(',').map((value) => value.trim()).filter(Boolean), sourceStatusAfter: row.querySelector('.workflow-action-source-status').value, caseStatusAfter: row.querySelector('.workflow-action-case-status').value, recipientCategory: row.querySelector('.workflow-action-recipient-category').value, repeatable: row.querySelector('.workflow-action-repeatable').checked }))
			if (!actions.length) { notifyError('Ein Workflow benötigt mindestens eine Folgeaktion.'); return }
			const current = state.workflowAdmin.find((entry) => Number(entry.id) === id); const payload = { ...data, triggerConfig: { schedulePresetKeys: String(data.schedulePresetKeys || '').split(',').map((value) => value.trim()).filter(Boolean) }, active: form.elements.active.checked, sortOrder: Number(current?.sortOrder || (state.workflowAdmin.length * 10)), actions }; delete payload.schedulePresetKeys
			const status = document.getElementById('workflow-form-state'); const submit = document.getElementById('save-workflow'); submit.disabled = true; status.textContent = 'Workflow wird gespeichert …'; status.dataset.state = 'saving'
			try { const saved = await api(id ? `${workflowUrl()}/${id}` : workflowUrl(), { method: id ? 'PUT' : 'POST', feedback: false, body: new URLSearchParams({ workflow: JSON.stringify(payload) }) }); state.workflowAdmin = await api(workflowUrl()); state.workflowAdminId = Number(saved.id); globalThis.localStorage?.setItem('bestatter:workflow-admin-id', String(saved.id)); render(); notifySuccess('Der Workflow einschließlich aller Folgeaktionen wurde gespeichert.') } catch (error) { status.textContent = error.message; status.dataset.state = 'error'; submit.disabled = false }
		})
		root.querySelector('.cancel-new-workflow')?.addEventListener('click', () => { state.workflowAdmin = state.workflowAdmin.filter((entry) => Number(entry.id) !== 0); state.workflowAdminId = Number(state.workflowAdmin[0]?.id || 0); render() })
		root.querySelectorAll('.delete-workflow').forEach((button) => button.addEventListener('click', async () => {
			if (!await confirmAction('Workflow einschließlich Ausführungsprotokoll wirklich löschen?', { title: 'Workflow löschen', confirmLabel: 'Löschen', danger: true })) return
			await api(`${workflowUrl()}/${button.dataset.workflowId}`, { method: 'DELETE' })
			state.workflowAdmin = await api(workflowUrl()); state.workflowAdminId = Number(state.workflowAdmin[0]?.id || 0); globalThis.localStorage?.setItem('bestatter:workflow-admin-id', String(state.workflowAdminId)); render()
		}))
		const workflowOrder = document.getElementById('workflow-order-rows')
		const saveWorkflowOrder = async () => { const ids = [...workflowOrder.querySelectorAll('[data-workflow-order-row]')].map((row) => Number(row.dataset.workflowOrderRow)); if (ids.includes(0)) { notifyError('Den neuen Workflow bitte zuerst speichern; danach kann die Reihenfolge geändert werden.'); return } try { state.workflowAdmin = await api(`${workflowUrl()}/reorder`, { method: 'PUT', feedback: false, body: new URLSearchParams({ workflowIds: JSON.stringify(ids) }) }); render(); notifySuccess('Die Workflow-Reihenfolge wurde gespeichert.') } catch (error) { state.workflowAdmin = await api(workflowUrl()); render(); notifyError(error.message) } }
		workflowOrder?.querySelectorAll('[data-workflow-order-row]').forEach((row) => { const handle = row.querySelector('[data-drag-kind="workflow"]'); if (!handle) return; handle.addEventListener('dragstart', (event) => { workflowOrder._bpDraggedRow = row; row.classList.add('is-dragging'); event.dataTransfer.effectAllowed = 'move' }); handle.addEventListener('dragend', () => { row.classList.remove('is-dragging'); workflowOrder._bpDraggedRow = null }); handle.addEventListener('keydown', async (event) => { if (!event.altKey || !['ArrowUp','ArrowDown'].includes(event.key)) return; event.preventDefault(); const sibling = event.key === 'ArrowUp' ? row.previousElementSibling : row.nextElementSibling; if (!sibling) return; workflowOrder.insertBefore(row, event.key === 'ArrowUp' ? sibling : sibling.nextElementSibling); await saveWorkflowOrder() }) })
		workflowOrder?.addEventListener('dragover', (event) => { const dragged = workflowOrder._bpDraggedRow; const target = event.target.closest('[data-workflow-order-row]'); if (!dragged || !target || target === dragged) return; event.preventDefault(); target.classList.add('is-drag-target') })
		workflowOrder?.addEventListener('dragleave', (event) => event.target.closest('[data-workflow-order-row]')?.classList.remove('is-drag-target'))
		workflowOrder?.addEventListener('drop', async (event) => { const dragged = workflowOrder._bpDraggedRow; const target = event.target.closest('[data-workflow-order-row]'); if (!dragged || !target || target === dragged) return; event.preventDefault(); const after = event.clientY > target.getBoundingClientRect().top + target.getBoundingClientRect().height / 2; workflowOrder.insertBefore(dragged, after ? target.nextSibling : target); target.classList.remove('is-drag-target'); await saveWorkflowOrder() })
	}


	return { documentTemplatesView, deregistrationTemplatesView, workflowAdminView, workflowActionRows, showWorkflowForm, customizing, bindCustomizing, bindConfigurationAdministration, bindWorkflowAdmin, schedulingView }
}
